from enum import Enum


class ValidationErrorType(str, Enum):
    INVALID_AMOUNT       = "INVALID_AMOUNT"
    INVALID_USERNAME     = "INVALID_USERNAME"
    INVALID_EMAIL        = "INVALID_EMAIL"
    INVALID_PROBABILITY  = "INVALID_PROBABILITY"
    INVALID_STAKE        = "INVALID_STAKE"
    INVALID_RANGE        = "INVALID_RANGE"
    REQUIRED_FIELD       = "REQUIRED_FIELD"
    DUPLICATE_ENTRY      = "DUPLICATE_ENTRY"
    INSUFFICIENT_FUNDS   = "INSUFFICIENT_FUNDS"
    BOUNDARY_VIOLATION   = "BOUNDARY_VIOLATION"
